# Generated by Django 2.2.5 on 2019-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Ended', 'Ended')], default='Not Started', max_length=10),
        ),
    ]
