# Generated by Django 2.2.5 on 2019-11-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='sprint_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
