# Generated by Django 2.2.5 on 2019-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0002_sprint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Started', 'Started'), ('Ended', 'Ended')], default='Not Started', max_length=20),
        ),
    ]
