# Generated by Django 2.2.5 on 2019-11-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0002_sprint_sprint_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('doing', 'Doing'), ('done', 'Done')], default='To Do', max_length=5),
        ),
    ]
