# Generated by Django 2.2.5 on 2019-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0003_auto_20191116_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
