# Generated by Django 2.2.6 on 2019-11-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0003_auto_20191102_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=5),
        ),
    ]
