# Generated by Django 2.2.6 on 2019-11-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0004_auto_20191104_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='sprint_number',
        ),
    ]
