# Generated by Django 2.2.6 on 2019-11-10 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0007_auto_20191109_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2019, 11, 11), null=True),
        ),
    ]
