# Generated by Django 2.2.7 on 2019-11-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('users', '0004_remove_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
