# Generated by Django 2.2.6 on 2019-11-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191120_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='project_id',
            new_name='project',
        ),
    ]
