# Generated by Django 2.2.6 on 2019-11-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_duration'),
        ('users', '0007_auto_20191120_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='project',
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
