# Generated by Django 2.2.7 on 2019-11-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191120_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
