# Generated by Django 2.2.5 on 2019-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='project.Project'),
        ),
    ]
