# Generated by Django 2.2.6 on 2019-10-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('title', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('ESP', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
