# Generated by Django 2.2.5 on 2019-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PBIs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('title', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=5)),
                ('ESP', models.IntegerField()),
                ('sprint_number', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
    ]
