# Generated by Django 2.2.6 on 2019-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productBacklog', '0001_initial'),
        ('sprintBacklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='sprint',
            field=models.ManyToManyField(to='sprintBacklog.Sprint'),
        ),
    ]
