# Generated by Django 2.2.6 on 2019-10-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbis',
            name='sprint_number',
        ),
    ]
