# Generated by Django 2.2.6 on 2019-10-25 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0002_remove_pbis_sprint_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbis',
            name='itemID',
        ),
    ]
