# Generated by Django 2.2.5 on 2019-11-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0002_pbi_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Unfinished', 'Unfinished')], default='To Do', max_length=5),
        ),
    ]
