# Generated by Django 2.2.5 on 2019-11-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0003_auto_20191116_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done'), ('Unfinished', 'Unfinished')], default='To Do', max_length=20),
        ),
    ]
