# Generated by Django 2.2.5 on 2019-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0004_auto_20191116_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbi',
            name='sprint',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='sprintBacklog.Sprint'),
        ),
    ]
