# Generated by Django 2.2.5 on 2019-10-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0004_auto_20191025_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbis',
            name='project_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
