# Generated by Django 2.2.6 on 2019-10-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0005_auto_20191025_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pbis',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
    ]
