# Generated by Django 2.2.5 on 2019-10-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0005_auto_20191025_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pbis',
            old_name='project_id',
            new_name='project',
        ),
    ]
