# Generated by Django 2.2.5 on 2019-10-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0006_auto_20191026_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbis',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
