# Generated by Django 2.2.5 on 2019-10-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productBacklog', '0007_pbis_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbis',
            name='slug',
        ),
    ]
