# Generated by Django 2.2.5 on 2019-11-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprintBacklog', '0001_initial'),
        ('productBacklog', '0009_auto_20191101_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbi',
            name='sprint',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprintBacklog.Sprint'),
        ),
        migrations.AlterField(
            model_name='pbi',
            name='ESP',
            field=models.IntegerField(verbose_name='estimated story point'),
        ),
    ]
