# Generated by Django 2.2.7 on 2019-11-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
