# Generated by Django 2.2.5 on 2019-11-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='duration(week)'),
        ),
    ]
