# Generated by Django 2.2.6 on 2019-11-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=2, verbose_name='Sprint Duration(week)'),
        ),
    ]
